### PR TITLE
Custom style for Android default picker

### PR DESCRIPTION
**Pull request by alessiocancian**
Added itemStyleAndroid which allows to set custom style for each item of the default Android picker.
Added selectedItemStyleAndroid which allows to set custom style for the selected item.

### CODE REVIEW

**Comment by Valiums** [comment]
@alessiocancian Thanks for your PR! I'll review and merge any soon !

**Comment by alessiocancian** [comment]
@Valiums Any problems with the merge?

I added another option to customize the style of the modal.
If you don't like the names of the options you can change them however you want.

**Comment by Valiums** [comment]
@alessiocancian very sorry! No, nothing wrong at all, just had no time to review, got very busy.

**Comment by Valiums** [comment]
@alessiocancian great work man! merging!

**Comment by Valiums** [comment]
@alessiocancian live on 1.2.0! Thanks!

**Pull request merged**
